Repository elementary/greeter, pull requests merged in 2018-11, with the labels that each got.

#191 BackgroundImage: Fix light bleed on corners
  src/Cards/BackgroundImage.vala
Labels: Bitesize

#197 Grab entry focus when typing
  src/Cards/ManualCard.vala
  src/Cards/UserCard.vala
  src/MainWindow.vala
Labels: Help Wanted, Status: In Progress

#181 New Greeter using only Gtk+
  compositor/SystemBackground.vala
  compositor/Wallpaper.vala
  compositor/WindowManager.vala
  compositor/meson.build
  data/Card.css
  data/DateTime.css
  data/Greeter.css
  data/compositor.gresource.xml
  data/greeter.gresource.xml
  data/texture.png
  meson.build
  src/Application.vala
  src/CapsLockRevealer.vala
  src/Cards/BackgroundImage.vala
  src/Cards/BaseCard.vala
  src/Cards/ManualCard.vala
  src/Cards/UserCard.vala
  src/ComponentWatcher.vala
  src/Credentials/Credentials.vala
  src/Credentials/FingerprintCredentials.vala
  src/Credentials/LoginButtonCredentials.vala
  src/Credentials/PasswordCredentials.vala
  src/DateTimeWidget.vala
  src/FPrintUtils.vala
  src/Gateways/DummyGateway.vala
  src/Gateways/LightDMGateway.vala
  src/Gateways/LoginGateway.vala
  src/LoginMask.vala
  src/LoginOptions/GuestLogin.vala
  src/LoginOptions/LoginOption.vala
  src/LoginOptions/ManualLogin.vala
  src/LoginOptions/UserLogin.vala
  src/MainWindow.vala
  src/PantheonGreeter.vala
  src/PasswordEntry.vala
  src/PromptText.vala
  src/SessionButton.vala
  src/Settings.vala
  src/SettingsDaemon.vala
  src/SubprocessSupervisor.vala
  src/UserList.vala
  src/UserListActor.vala
  src/Widgets/CredentialsArea.vala
  src/Widgets/LoginBox.vala
  src/Widgets/TimeLabel.vala
  src/Widgets/Wallpaper.vala
  src/meson.build
Labels: Priority: Wishlist
